[window]
opacity = 0.90
decorations = "none"
dynamic_padding = true

[window.padding]
x = 6
y = 6

[font]
normal = { family = "GohuFont 14 Nerd Font", style = "Regular" }
size = 14.0

[colors]
[colors.primary]
background = "#000000"
