[window]
opacity = 0.95
decorations = "none"
dynamic_padding = true

[window.padding]
x = 0
y = 0

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
size = 16.0

[colors]
[colors.primary]
background = "#000000"
