[window]
opacity = 1
decorations = "none"

[window.padding]
x = 0
y = 0

[font]
normal = { family = "GohuFont 14 Nerd Font", style = "Regular" }
size = 14.0

[colors]
[colors.primary]
background = "#000000"
