start-at-login = true
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# Run Sketchybar together with AeroSpace
after-startup-command = ['exec-and-forget sketchybar']

# Notify Sketchybar about workspace change
exec-on-workspace-change = ['/bin/bash', '-c',
    'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE'
]

[gaps]
inner.horizontal = 4
inner.vertical = 4
outer.left = 0
outer.bottom = 0
outer.top = [{ monitor."LF27T450F" = 38 }, 0]
outer.right = 0

[key-mapping]
preset = 'qwerty'

[mode.main.binding]
alt-enter = '''exec-and-forget osascript -e '
tell application "alacritty"
    do script ""
    activate
end tell'
'''

# Window focus (vim-style)
alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

# Move windows
alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

# Workspace switching
alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'
alt-0 = 'workspace 10'
alt-b = 'workspace B'
alt-c = 'workspace C'
alt-t = 'workspace T'
alt-w = 'workspace W'

# Move containers to workspace
alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-7 = 'move-node-to-workspace 7'
alt-shift-8 = 'move-node-to-workspace 8'
alt-shift-9 = 'move-node-to-workspace 9'
alt-shift-0 = 'move-node-to-workspace 10'
alt-shift-b = 'move-node-to-workspace B'
alt-shift-c = 'move-node-to-workspace C'
alt-shift-t = 'move-node-to-workspace T'
alt-shift-w = 'move-node-to-workspace W'

# Layout controls
alt-e = 'layout tiles horizontal'  # horizontal split
alt-v = 'layout tiles vertical'    # vertical split
alt-m = 'layout accordion'  # accordion layout (fullscreen-like)

# Workspace navigation (similar to your i3 tab bindings)
alt-tab = 'workspace-back-and-forth'
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

# Kill window (equivalent to your i3 alt+shift+q)
alt-shift-q = 'close'

# Resize
alt-shift-minus = 'resize smart -50'
alt-shift-equal = 'resize smart +50'

# Enter service mode (for additional commands)
alt-shift-semicolon = 'mode service'

[mode.service.binding]
# Exit service mode
esc = ['reload-config', 'mode main']

# Reset layout
r = ['flatten-workspace-tree', 'mode main']

# Layout toggles
f = ['layout floating tiling', 'mode main']

# Close all windows except current
backspace = ['close-all-windows-but-current', 'mode main']

# Window joining
alt-shift-h = ['join-with left', 'mode main']
alt-shift-j = ['join-with down', 'mode main']
alt-shift-k = ['join-with up', 'mode main']
alt-shift-l = ['join-with right', 'mode main']
