#!/bin/bash

source "$CONFIG_DIR/colors.sh"

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

##### Bar Appearance #####
sketchybar --bar height=32 \
    blur_radius=0 \
    position=top \
    padding_left=16 \
    padding_right=16 \
    color=$BACKGROUND_COLOR

##### Changing Defaults #####
sketchybar --default icon.font="GohuFont 14 Nerd Font:Regular:14.0" \
    icon.color=$ITEM_COLOR \
    icon.padding_left=4 \
    icon.padding_right=2 \
    label.padding_left=4 \
    label.padding_right=6 \
    label.font="GohuFont 14 Nerd Font:Regular:14.0" \
    label.color=$ITEM_COLOR \
    background.height=32 \

# -- Left Side Items --
source $ITEM_DIR/spaces.sh
source $ITEM_DIR/front-app.sh

# -- Right Side Items --
source $ITEM_DIR/calendar.sh

sketchybar --update
